---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ravindrasinghh/argocd-setup.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACARU1MpwraesVSqzMnVJE25Sbt11WaeRJZ6J6H2TlLg0wAAAKCnzPQzp8z0
    MwAAAAtzc2gtZWQyNTUxOQAAACARU1MpwraesVSqzMnVJE25Sbt11WaeRJZ6J6H2TlLg0w
    AAAED0GjSvHL24mXb1L3K27lZlGTjSXVCQdiUvdJWcpJ6hbxFTUynCtp6xVKrMydUkTblJ
    u3XVZp5ElnonofZOUuDTAAAAGmFwcGxlQFJhdmluZHJhLVNpbmdoLmxvY2FsAQID
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"


# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd

