name: Deploy to Kubernetes

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${DOCKER_USERNAME}/my-app:$GITHUB_RUN_NUMBER -f argocd-cicd-setup/Dockerfile .
          docker push ${DOCKER_USERNAME}/my-app:$GITHUB_RUN_NUMBER
      - name: Login to GitHub Packages
        uses: actions/checkout@v3
        with:
          repository: ravindrasinghh/argocd-setup
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}
      
      # Update the image tag in Kubernetes deployment YAML file
      - name: Update deployment YAML
        run: |
          sed -i'' "s|${DOCKER_USERNAME}/my-app:.*|${DOCKER_USERNAME}/my-app:$GITHUB_RUN_NUMBER|" argocd-cicd-setup/dev/deployment.yaml
          cat argocd-cicd-setup/dev/deployment.yaml
      - name: Commit and push changes
        run: |
          git config --global user.email "ravindrasinghh.me@gmail.com"
          git config --global user.name "ravindrasinghh"
          git add argocd-cicd-setup/dev/deployment.yaml
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push origin master
